[default]
SQLALCHEMY_DATABASE_URI = "mysql://admin:admin@database:3306/main"
TITLE = "user_service"
EXTENSIONS = [
    "src.ext.configuration:init_app",
    "src.ext.database:init_app",
    "src.blueprints.routes.routes:init_app",
]
PUBLIC_KEY = "thisisthesecretkey"
SECRET_KEY = "1a2b3c4d"
